source 'https://rubygems.org'

gem 'aasm'
gem 'angular-rails-templates'
gem 'angular_rails_csrf'
gem 'angularjs-file-upload-rails', '~> 2.2.0'
gem 'annotate'
gem 'attribute_normalizer'
gem 'auth_client', git: 'https://github.com/openteam-tusur/auth_client'
gem 'auth_redis_user_connector', git: 'https://github.com/openteam-tusur/auth_redis_user_connector'
gem 'auto_html'
gem 'awesome_print'
gem 'bootstrap-sass'
gem 'cancancan'
gem 'coffee-rails'
gem 'compass-rails'
gem 'enumerize'
gem 'esp-commons'
gem 'font-awesome-rails'
gem 'friendly_id'
gem 'geoip'
gem 'gilenson'
gem 'gravtastic'
gem 'hashie'
gem 'jbuilder'
gem 'jquery-colorbox-rails'
gem 'jquery-rails', '~> 2.1.4'
gem 'jquery-ui-rails'
gem 'kaminari'
gem 'mechanize'
gem 'ngannotate-rails'
gem 'nokogiri'
gem 'non-stupid-digest-assets'
gem 'openteam-commons', '~> 0.3.3'
gem 'paper_trail'
gem 'paperclip'
gem 'pg'
gem 'postman-client', git: 'https://github.com/openteam-tusur/postman-client'
gem 'progress_bar', require: false
gem 'rack-cache'
gem 'rack-utf8_sanitizer'
gem 'rails', '~> 4.2.0'
gem 'ranked-model'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'redis-session-store'
gem 'rest-client', '~> 1.8.0'
gem 'rest-client-components'
gem 'russian'
gem 'sass-rails'
gem 'sidekiq'
gem 'simple-navigation'
gem 'simple_form'
gem 'sinatra', require: nil
gem 'sitemap_generator'
gem 'stop_ie'
gem 'sunspot_rails'
gem 'time_diff'
gem 'truncate_html'
gem 'tusur_header', '~> 0.2.9'
gem 'uglifier'
gem 'whenever'
gem 'yajl-ruby', require: 'yajl'
gem 'yt'

source 'https://rails-assets.org' do
  gem 'rails-assets-chosen'
  gem 'rails-assets-galleria'
  gem 'rails-assets-jcarousel'
  gem 'rails-assets-jquery-animatenumber'
  gem 'rails-assets-jquery-touchswipe'
  gem 'rails-assets-jquery.scrollTo'
  gem 'rails-assets-sugar'
  gem 'rails-assets-tinyscrollbar'
  gem 'rails-assets-waypoints'
  gem 'rails-assets-angular-bootstrap'

  #angular assets stuff
  gem 'rails-assets-angular'
  gem 'rails-assets-angular-ui-router'
  gem 'rails-assets-angular-ui-sortable'
  gem 'rails-assets-angucomplete-alt'
  gem 'rails-assets-bootstrap-datepicker'
  gem 'rails-assets-moment'
  gem 'rails-assets-ng-file-upload'
end

group :development do
  gem 'brakeman', require: false
  gem 'capistrano-auth-subscriber'
  gem 'foreman'
  gem 'letter_opener'
  gem 'openteam-capistrano', '~> 1.0.16'
  gem 'quiet_assets' #, :require => false
  gem 'rails-erd'
  gem 'ryba'
end

group :test do
  gem 'rspec-rails'
  gem 'sqlite3'
end

group :production do
  gem 'unicorn'
end
