science_degree:
  дархн: доктор архитектурных наук
  дбн: доктор биологических наук
  двн: доктор ветеринарных наук
  двоенн:  доктор военных наук
  дгн: доктор географических наук
  дгмн:  доктор геолого-минералогических наук
  диск:  доктор искусствоведения
  дин: доктор исторических наук
  дмн: доктор медицинских наук
  дпн: доктор педагогических наук
  дполн: доктор политологических наук
  дпсхн: доктор психологических наук
  дсхн:  доктор сельскохозяйственных наук
  дсоцн: доктор социологических наук
  дтн: доктор технических наук
  дфармн:  доктор фармацевтических наук
  дфмн:  доктор физико-математических наук
  дфилн: доктор филологических наук
  дфн: доктор философских наук
  дхн: доктор химических наук
  дэн: доктор экономических наук
  дюн: доктор юридических наук
  кархн: кандидат архитектурных наук
  кбн: кандидат биологических наук
  квн: кандидат ветеринарных наук
  квоенн: кандидат военных наук
  кгн: кандидат географических наук
  кгмн:  кандидат геолого-минералогических наук
  киск:  кандидат искусствоведения
  кин: кандидат исторических наук
  кмн: кандидат медицинских наук
  кпн: кандидат педагогических наук
  кполн: кандидат политологических наук
  кпсхн: кандидат психологических наук
  ксхн:  кандидат сельскохозяйственных наук
  ксоцн: кандидат социологических наук
  ктн: кандидат технических наук
  кфмн:  кандидат физико-математических наук
  кфармн:  кандидат фармацевтических наук
  кфилн: кандидат филологических наук
  кфн: кандидат философских наук
  кхн: кандидат химических наук
  кэн: кандидат экономических наук
  кюн: кандидат юридических наук
  б/с: без ученой степени
science_title:
  акад: Академик РАН
  проф.: Профессор
  доц: Доцент
  снс: Старший научный сотрудник
  б/з: без ученого звания
